### ISSUE TITLE
Incidencia

### ISSUE THREAD

**Issue by alu0100658705** [ULL-ESIT-DSI-1920/dsi-p8-docker-alu0100658705#3]
Buenas noches @ManzDev 
Acabo de ver en el correo que tengo una incidencia en Slack, pero lo que usted expone ya lo tengo implementado en la práctica. ¿Hay algo que no haya hecho bien?

Saludos, Pablo Bethencourt

**Comment by alu0100658705** [comment]
Hola de nuevo, acabo de entrar en Slack y al parecer hubo una confusión con los nombres e iba dirigido a otro Pablo. 

Aprovecho para comentar que mañana intentará realizar una nueva entrega ampliando la práctica. Cierro la incidencia.

Disculpe. Saludos, Pablo Bethencourt

**Comment by ManzDev** [comment]
Hola Pablo,

Disculpa, no me di cuenta y debí citar mal.
Perfecto, gracias por avisar!

Saludos,
