### ISSUE TITLE
Duda nginx imágenes

### ISSUE THREAD

**Issue by alu0100658705** [ULL-ESIT-DSI-1920/dsi-p8-docker-alu0100658705#4]
Buenos días @ManzDev 

Aunque ya no creo que realice una segunda entrega de la práctica con mejoras, si que me gustaría solventar esta duda con la que llevo toda la mañana:

Estoy tratando de traer imágenes desde el backend. He estado probando y, para traer archivos estáticos desde una determinada carpeta, me puede servir la siguiente directiva:
`app.use('/images', express.static(__dirname + '/public/images'));`

Luego, en el archivo de configuración de nginx, tengo: 
`
 location ^~ /images/.+\.PNG$ {
        proxy_pass http://node:8081/$1;
    }
`
Aquí ya me surge la primera duda, si utilizo expresiones regulares para pedir cada una de las imágenes, en el _proxy_pass_ entiendo que $1 me toma la expresión completa (/images/Hulk.png, por ejemplo), sin embargo me está saliendo un error donde no logra encontrar la ruta definida...

El código del index.js trás muchas pruebas:
`
		const h_image = document.createElement('img');
		const ruta = '/images/' + heroes[i].image; 
		const r_img = await fetch(ruta);
		const blob = await r_img.blob();
		h_image.srcset = URL.createObjectURL(blob);
`
¿Qué podría estar haciendo mal?, ¿Cuál es la forma más óptima de hacerlo?

Muchas gracias, saludos, Pablo  Bethencourt.

**Comment by ManzDev** [comment]
Hola Pablo!

En principio, y en este caso particular, creo que las imágenes tendría más sentido que las sirvieras desde el frontend, ya que parcel se encarga de ello y se pueden enlazar fácilmente desde HTML, CSS o JS. Incluso se pueden enlazar a un `imagemin` y se optimizan solas.

Aún así, si quieres tenerlas desde el backend, yo haría algo parecido a lo siguiente (lo escribo de memoria, revisalas bien, que las regexp son muy traicioneras):

```
location ~* ^/images/.+\.(jpeg|gif|png|jpg)$ {
}
```

Con eso le indico:

- `^` Ancla de expresión regular: cuando la petición empieza por
- `/images/` pide algo dentro de la carpeta `images`
- `.+` Cualquier cosa repetida 1 o más veces
- `\.(jpeg|gif|png|jpg)$` que termine en las extensiones `.jpeg`, `.gif`, `.png`, `.jpg`
- Ten en cuenta que linux es sensible a mayusculas/minusculas

Si no recuerdo mal, nginx usa `$1` cuando capturas algo entre paréntesis en una regexp. Es decir, como en tu ejemplo no tienes paréntesis, no captura nada (eso si no es por el tema de PNG en mayúsculas).

A ver si eso te sirve para encaminarlo.

¡Saludos!

**Comment by alu0100658705** [comment]
Genial, ¡Muchas gracias! tiene mejor pinta.
Saludos, Pablo
